server:
  port: 8192
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/komalvhanmane/spring-cloud-config-store
          search-paths:
           - '*service'



